In [57]:
import requests
import warnings
from tqdm import tqdm, trange
import streamlit as st
import pandas as pd 
import yfinance as yf
from datetime import datetime
from dateutil.relativedelta import relativedelta
import plotly_express  as px
import plotly.graph_objects as go
import random
import unittest
import tables
import pickle
import pyarrow.parquet as pq
import pyarrow as pa
import plotly.io as pio
import math
import investpy
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import subprocess
import numpy as np
import matplotlib.pyplot as plt
import datetime
import time
from datetime import datetime
import pandas as pd
import streamlit as st
import yfinance as yf
import plotly.graph_objects as go
from streamlit_option_menu import option_menu
import math
import numpy as np
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import subprocess
import time
import requests
import os
from stqdm import stqdm
from sklearn.manifold import TSNE
import plotly_express as px
import ast
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

In [2]:
API_KEY = "6ulfs8VItWZcKZTMzNJxwmikpQvSF1cI"

In [3]:
pio.templates.default = "plotly_dark"

In [231]:
temp_df = pd.DataFrame(requests.get(f"https://financialmodelingprep.com/stable/historical-price-eod/light?symbol=AAPL&apikey={API_KEY}").json())
temp_df = temp_df.drop(columns=['symbol', 'volume'])
temp_df['date'] = pd.to_datetime(temp_df['date'])
temp_df = temp_df.set_index('date')
temp_df

             price
date
2025-07-18  211.18
2025-07-17  210.02
2025-07-16  210.16
2025-07-15  209.11
2025-07-14  208.62
...            ...
2020-07-27   94.81
2020-07-24   92.62
2020-07-23   92.85
2020-07-22   97.27
2020-07-21   97.00

[1255 rows x 1 columns]

In [232]:
temp_df = pd.DataFrame(requests.get(f"https://financialmodelingprep.com/stable/historical-price-eod/light?symbol=MSFT&apikey={API_KEY}").json())
temp_df = temp_df.drop(columns=['symbol', 'volume'])
temp_df['date'] = pd.to_datetime(temp_df['date'])
temp_df = temp_df.set_index('date')
temp_df

             price
date
2025-07-18  510.05
2025-07-17  511.70
2025-07-16  505.62
2025-07-15  505.82
2025-07-14  503.02
...            ...
2020-07-27  203.85
2020-07-24  201.30
2020-07-23  202.54
2020-07-22  211.75
2020-07-21  208.75

[1255 rows x 1 columns]

In [239]:
raw_data = pd.DataFrame(temp_df.index)
raw_data = raw_data.set_index("date")
raw_data

Empty DataFrame
Columns: []
Index: [2025-07-18 00:00:00, 2025-07-17 00:00:00, 2025-07-16 00:00:00, 2025-07-15 00:00:00, 2025-07-14 00:00:00, 2025-07-11 00:00:00, 2025-07-10 00:00:00, 2025-07-09 00:00:00, 2025-07-08 00:00:00, 2025-07-07 00:00:00, 2025-07-03 00:00:00, 2025-07-02 00:00:00, 2025-07-01 00:00:00, 2025-06-30 00:00:00, 2025-06-27 00:00:00, 2025-06-26 00:00:00, 2025-06-25 00:00:00, 2025-06-24 00:00:00, 2025-06-23 00:00:00, 2025-06-20 00:00:00, 2025-06-18 00:00:00, 2025-06-17 00:00:00, 2025-06-16 00:00:00, 2025-06-13 00:00:00, 2025-06-12 00:00:00, 2025-06-11 00:00:00, 2025-06-10 00:00:00, 2025-06-09 00:00:00, 2025-06-06 00:00:00, 2025-06-05 00:00:00, 2025-06-04 00:00:00, 2025-06-03 00:00:00, 2025-06-02 00:00:00, 2025-05-30 00:00:00, 2025-05-29 00:00:00, 2025-05-28 00:00:00, 2025-05-27 00:00:00, 2025-05-23 00:00:00, 2025-05-22 00:00:00, 2025-05-21 00:00:00, 2025-05-20 00:00:00, 2025-05-19 00:00:00, 2025-05-16 00:00:00, 2025-05-15 00:00:00, 2025-05-14 00:00:00, 2025-05-13 00:00:00, 2025-05-12 00:00:00, 2025-05-09 00:00:00, 2025-05-08 00:00:00, 2025-05-07 00:00:00, 2025-05-06 00:00:00, 2025-05-05 00:00:00, 2025-05-02 00:00:00, 2025-05-01 00:00:00, 2025-04-30 00:00:00, 2025-04-29 00:00:00, 2025-04-28 00:00:00, 2025-04-25 00:00:00, 2025-04-24 00:00:00, 2025-04-23 00:00:00, 2025-04-22 00:00:00, 2025-04-21 00:00:00, 2025-04-17 00:00:00, 2025-04-16 00:00:00, 2025-04-15 00:00:00, 2025-04-14 00:00:00, 2025-04-11 00:00:00, 2025-04-10 00:00:00, 2025-04-09 00:00:00, 2025-04-08 00:00:00, 2025-04-07 00:00:00, 2025-04-04 00:00:00, 2025-04-03 00:00:00, 2025-04-02 00:00:00, 2025-04-01 00:00:00, 2025-03-31 00:00:00, 2025-03-28 00:00:00, 2025-03-27 00:00:00, 2025-03-26 00:00:00, 2025-03-25 00:00:00, 2025-03-24 00:00:00, 2025-03-21 00:00:00, 2025-03-20 00:00:00, 2025-03-19 00:00:00, 2025-03-18 00:00:00, 2025-03-17 00:00:00, 2025-03-14 00:00:00, 2025-03-13 00:00:00, 2025-03-12 00:00:00, 2025-03-11 00:00:00, 2025-03-10 00:00:00, 2025-03-07 00:00:00, 2025-03-06 00:00:00, 2025-03-05 00:00:00, 2025-03-04 00:00:00, 2025-03-03 00:00:00, 2025-02-28 00:00:00, 2025-02-27 00:00:00, 2025-02-26 00:00:00, 2025-02-25 00:00:00, ...]

[1255 rows x 0 columns]

In [241]:
temp_df["price"].values.tolist()

[510.05,
 511.7,
 505.62,
 505.82,
 503.02,
 503.32,
 501.48,
 503.51,
 496.62,
 497.72,
 498.84,
 491.09,
 492.05,
 497.41,
 495.94,
 497.45,
 492.27,
 490.11,
 486.0,
 477.4,
 480.24,
 478.04,
 479.14,
 474.96,
 478.87,
 472.62,
 470.92,
 472.75,
 470.38,
 467.68,
 463.87,
 462.97,
 461.97,
 460.36,
 458.68,
 457.36,
 460.69,
 450.18,
 454.86,
 452.57,
 458.17,
 458.87,
 454.27,
 453.13,
 452.94,
 449.14,
 449.26,
 438.73,
 438.17,
 433.35,
 433.31,
 436.17,
 435.28,
 425.4,
 395.26,
 394.04,
 391.16,
 391.85,
 387.3,
 374.39,
 366.82,
 359.12,
 367.78,
 371.61,
 385.73,
 387.81,
 388.45,
 381.35,
 390.49,
 354.56,
 357.86,
 359.84,
 373.11,
 382.14,
 382.19,
 375.39,
 378.8,
 390.58,
 389.97,
 395.16,
 393.08,
 391.26,
 386.84,
 387.82,
 383.52,
 388.7,
 388.56,
 378.77,
 383.27,
 380.45,
 380.16,
 393.31,
 396.89,
 401.02,
 388.61,
 388.49,
 396.99,
 392.53,
 399.73,
 397.9,
 404.0,
 408.21,
 416.13,
 414.77,
 409.64,
 408.43,
 410.54,
 409.04,
 411.44,
 412.22,
 409.75,
 415.82,
 413.29,
 412.37,
 410.92,
 415.06,
 414.99,
 442.33,
 447.2,
 434.56,
 444.06,
 446.71,
 446.2,
 428.5,
 429.03,
 424.58,
 426.31,
 415.67,
 417.19,
 418.95,
 424.56,
 422.37,
 427.85,
 423.35,
 418.58,
 421.5,
 424.83,
 430.53,
 438.11,
 439.33,
 435.25,
 436.6,
 437.03,
 437.39,
 454.46,
 451.59,
 447.27,
 449.56,
 448.99,
 443.33,
 446.02,
 443.57,
 442.62,
 437.42,
 431.2,
 430.98,
 423.46,
 422.99,
 427.99,
 418.79,
 417.0,
 412.87,
 415.49,
 417.79,
 415.76,
 415.0,
 426.89,
 425.2,
 423.03,
 418.01,
 422.54,
 425.43,
 420.18,
 411.46,
 408.46,
 410.37,
 406.35,
 432.53,
 431.95,
 426.59,
 428.15,
 424.73,
 424.6,
 427.51,
 418.78,
 418.16,
 416.72,
 416.12,
 418.74,
 419.14,
 416.32,
 415.84,
 417.46,
 414.71,
 409.54,
 416.06,
 416.54,
 417.13,
 420.69,
 430.3,
 428.02,
 431.31,
 432.11,
 429.17,
 433.51,
 435.27,
 438.69,
 430.81,
 435.15,
 431.34,
 430.59,
 427.0,
 423.04,
 414.2,
 405.72,
 401.7,
 408.39,
 408.9,
 409.44,
 417.14,
 413.12,
 410.6,
 413.84,
 413.49,
 416.79,
 415.55,
 424.14,
 424.8,
 421.53,
 418.47,
 421.03,
 416.86,
 414.01,
 406.81,
 406.02,
 402.69,
 398.43,
 399.61,
 395.15,
 408.49,
 417.11,
 418.35,
 422.92,
 426.73,
 425.27,
 418.4,
 428.9,
 444.85,
 442.94,
 437.11,
 440.37,
 443.52,
 449.52,
 453.96,
 453.55,
 454.7,
 466.25,
 459.54,
 466.24,
 467.56,
 460.77,
 459.28,
 456.73,
 446.95,
 452.85,
 452.16,
 450.95,
 447.67,
 449.78,
 445.7,
 446.34,
 448.37,
 442.57,
 441.58,
 441.06,
 432.68,
 427.87,
 423.85,
 424.52,
 424.01,
 416.07,
 413.52,
 415.13,
 414.67,
 429.17,
 430.32,
 430.16,
 427.0,
 430.52,
 429.04,
 425.34,
 420.21,
 420.99,
 423.08,
 416.56,
 413.72,
 414.74,
 412.32,
 410.54,
 409.34,
 413.54,
 406.66,
 397.84,
 394.94,
 389.33,
 402.25,
 406.32,
 399.04,
 409.06,
 407.57,
 400.96,
 399.12,
 404.27,
 411.84,
 414.58,
 413.64,
 421.9,
 427.93,
 423.26,
 426.28,
 424.59,
 425.52,
 417.88,
 420.45,
 421.44,
 424.57,
 420.72,
 421.43,
 421.65,
 422.86,
 428.74,
 429.37,
 425.23,
 421.41,
 417.32,
 416.42,
 425.22,
 415.1,
 415.28,
 404.52,
 406.22,
 409.14,
 402.09,
 402.65,
 414.92,
 415.5,
 413.64,
 407.72,
 407.48,
 407.54,
 410.34,
 411.65,
 402.18,
 402.79,
 404.06,
 406.56,
 409.49,
 406.32,
 415.26,
 420.55,
 414.11,
 414.05,
 405.49,
 405.65,
 411.22,
 403.78,
 397.58,
 408.59,
 409.72,
 403.93,
 404.87,
 402.56,
 398.9,
 396.51,
 398.67,
 393.87,
 389.47,
 390.27,
 388.47,
 384.63,
 382.77,
 375.79,
 374.69,
 367.75,
 367.94,
 370.6,
 370.87,
 376.04,
 375.28,
 374.07,
 374.66,
 374.58,
 373.54,
 370.62,
 373.26,
 372.65,
 370.73,
 365.93,
 374.37,
 374.38,
 371.3,
 374.23,
 370.95,
 368.8,
 372.52,
 369.14,
 374.51,
 378.91,
 378.85,
 382.7,
 378.61,
 377.43,
 377.85,
 373.07,
 377.44,
 369.85,
 376.17,
 369.67,
 370.27,
 366.68,
 369.67,
 360.69,
 363.2,
 360.53,
 356.53,
 352.8,
 348.32,
 346.07,
 338.11,
 337.31,
 329.81,
 327.89,
 340.67,
 330.53,
 329.32,
 326.67,
 331.32,
 330.11,
 332.06,
 332.64,
 327.73,
 331.16,
 332.42,
 328.39,
 329.82,
 327.26,
 319.36,
 318.96,
 313.39,
 321.8,
 315.75,
 313.64,
 312.79,
 312.14,
 317.54,
 317.01,
 319.53,
 320.77,
 328.65,
 329.06,
 330.22,
 338.7,
 336.06,
 331.77,
 337.94,
 334.27,
 329.91,
 332.88,
 333.55,
 328.66,
 327.76,
 328.79,
 328.41,
 323.7,
 322.98,
 319.97,
 327.0,
 322.46,
 321.88,
 316.48,
 316.88,
 320.4,
 321.86,
 324.04,
 321.01,
 322.93,
 322.23,
 326.05,
 330.11,
 327.78,
 326.66,
 327.5,
 336.34,
 335.92,
 338.37,
 330.72,
 337.77,
 350.98,
 345.11,
 343.77,
 346.87,
 355.08,
 359.49,
 345.73,
 345.24,
 342.66,
 337.2,
 332.47,
 331.83,
 337.22,
 341.27,
 338.15,
 337.99,
 340.54,
 335.05,
 335.85,
 334.57,
 328.6,
 335.02,
 339.71,
 333.56,
 338.05,
 342.33,
 348.1,
 337.34,
 334.29,
 331.85,
 326.79,
 325.26,
 323.38,
 333.68,
 335.94,
 335.4,
 332.58,
 328.39,
 331.21,
 332.89,
 325.92,
 313.85,
 315.26,
 321.18,
 318.34,
 318.52,
 314.0,
 311.74,
 309.46,
 308.97,
 310.11,
 312.31,
 307.0,
 308.65,
 310.65,
 305.41,
 304.4,
 305.41,
 305.56,
 307.26,
 304.83,
 295.37,
 275.42,
 281.77,
 285.76,
 286.11,
 288.45,
 288.37,
 288.8,
 286.14,
 289.84,
 283.49,
 282.83,
 289.39,
 291.6,
 284.34,
 287.18,
 287.23,
 288.3,
 284.05,
 280.51,
 275.23,
 276.38,
 280.57,
 277.66,
 272.29,
 273.78,
 272.23,
 279.43,
 276.2,
 265.44,
 260.79,
 253.92,
 248.59,
 252.32,
 253.7,
 254.15,
 256.87,
 255.29,
 251.11,
 246.27,
 249.42,
 250.16,
 249.22,
 254.77,
 251.51,
 252.67,
 258.06,
 262.15,
 269.32,
 272.17,
 271.32,
 263.1,
 263.62,
 266.73,
 267.56,
 256.77,
 258.35,
 264.6,
 252.75,
 247.81,
 242.71,
 248.16,
 248.0,
 240.61,
 242.04,
 242.58,
 240.22,
 231.93,
 235.81,
 240.35,
 239.23,
 238.51,
 235.77,
 228.85,
 227.12,
 224.93,
 222.31,
 229.1,
 239.58,
 239.82,
 241.01,
 234.53,
 236.96,
 238.73,
 238.19,
 244.43,
 241.8,
 240.45,
 244.69,
 249.01,
 257.22,
 256.92,
 252.51,
 245.42,
 247.4,
 244.37,
 245.12,
 250.2,
 255.02,
 254.69,
 255.14,
 240.33,
 241.76,
 247.49,
 247.58,
 245.03,
 242.05,
 241.22,
 241.68,
 241.73,
 241.97,
 241.55,
 247.11,
 242.98,
 224.51,
 228.87,
 227.87,
 221.39,
 214.25,
 220.1,
 228.17,
 232.13,
 235.87,
 226.75,
 231.32,
 250.66,
 247.25,
 242.12,
 236.15,
 236.48,
 238.5,
 237.53,
 228.56,
 234.24,
 225.75,
 225.41,
 229.25,
 234.24,
 246.79,
 249.2,
 248.88,
 240.74,
 232.9,
 237.5,
 241.07,
 236.41,
 237.45,
 237.92,
 240.98,
 238.95,
 242.45,
 244.52,
 244.74,
 245.38,
 252.22,
 251.99,
 266.65,
 264.46,
 258.52,
 258.09,
 253.25,
 256.06,
 260.4,
 261.47,
 262.97,
 265.23,
 268.09,
 278.85,
 275.79,
 276.44,
 277.75,
 286.15,
 290.17,
 291.32,
 292.71,
 293.47,
 291.91,
 287.02,
 289.16,
 282.3,
 280.32,
 282.91,
 283.65,
 282.47,
 274.82,
 278.01,
 280.74,
 276.41,
 268.74,
 251.9,
 258.83,
 260.36,
 264.84,
 262.27,
 259.53,
 254.25,
 256.72,
 254.08,
 252.72,
 253.67,
 264.51,
 267.66,
 268.4,
 266.21,
 262.85,
 259.58,
 256.83,
 260.26,
 256.48,
 264.89,
 267.7,
 258.86,
 253.13,
 253.74,
 247.65,
 244.97,
 251.76,
 244.49,
 242.26,
 252.99,
 264.79,
 270.41,
 272.5,
 268.75,
 270.02,
 274.58,
 272.42,
 271.87,
 273.24,
 265.9,
 262.52,
 259.62,
 260.65,
 252.56,
 253.14,
 254.08,
 266.82,
 261.5,
 261.12,
 255.35,
 260.55,
 269.5,
 264.58,
 274.73,
 277.35,
 289.98,
 281.78,
 284.47,
 277.52,
 289.63,
 283.22,
 270.22,
 280.72,
 274.03,
 280.81,
 286.36,
 285.3,
 280.52,
 279.83,
 287.62,
 282.06,
 285.26,
 296.97,
 301.37,
 299.5,
 310.88,
 314.97,
 309.42,
 308.31,
 313.86,
 315.41,
 310.7,
 303.68,
 304.1,
 299.49,
 304.06,
 299.16,
 300.43,
 295.22,
 294.39,
 287.15,
 276.44,
 280.07,
 285.59,
 288.5,
 275.85,
 278.91,
 289.86,
 295.92,
 300.19,
 294.95,
 298.79,
 297.31,
 294.59,
 280.27,
 287.72,
 287.93,
 290.73,
 299.5,
 300.47,
 295.0,
 295.04,
 302.38,
 311.21,
 304.56,
 300.95,
 305.94,
 301.25,
 313.46,
 308.76,
 310.98,
 308.26,
 299.84,
 296.71,
 288.49,
 296.37,
 296.03,
 301.6,
 303.33,
 302.65,
 310.2,
 304.8,
 318.27,
 314.98,
 314.27,
 314.04,
 313.88,
 316.38,
 329.01,
 334.75,
 336.32,
 339.32,
 341.95,
 341.25,
 342.45,
 334.69,
 333.2,
 327.29,
 319.91,
 323.8,
 324.9,
 334.65,
 328.34,
 339.4,
 342.54,
 333.1,
 334.97,
 334.92,
 326.19,
 323.01,
 329.49,
 330.08,
 330.59,
 336.63,
 329.68,
 337.91,
 337.68,
 339.83,
 343.11,
 341.27,
 339.12,
 339.51,
 336.07,
 336.72,
 332.43,
 330.8,
 335.95,
 336.99,
 336.06,
 336.44,
 334.0,
 333.13,
 329.37,
 331.62,
 324.35,
 323.17,
 310.11,
 308.13,
 309.16,
 310.76,
 307.41,
 308.23,
 307.29,
 304.21,
 302.75,
 296.31,
 292.88,
 294.23,
 294.85,
 294.85,
 293.11,
 288.76,
 283.11,
 289.1,
 281.92,
 284.0,
 283.52,
 294.17,
 299.35,
 299.56,
 298.58,
 294.8,
 294.3,
 299.87,
 305.22,
 304.82,
 299.79,
 296.99,
 295.71,
 297.25,
 300.21,
 300.18,
 301.14,
 301.15,
 301.83,
 301.88,
 303.59,
 299.72,
 299.09,
 302.01,
 302.62,
 304.65,
 304.36,
 296.77,
 290.73,
 293.08,
 294.6,
 292.85,
 289.81,
 286.95,
 286.44,
 288.33,
 289.46,
 289.52,
 286.51,
 287.12,
 284.82,
 284.91,
 286.5,
 286.22,
 286.54,
 289.05,
 ...]

In [249]:
cash_flow_stmnt = pd.DataFrame(requests.get(f"https://financialmodelingprep.com/stable/cash-flow-statement?symbol={ticker}&apikey={API_KEY}").json())
cash_flow_stmnt = cash_flow_stmnt.drop(columns=['symbol', 'reportedCurrency', 'cik','date','filingDate', 'acceptedDate', 'period' ])
cash_flow_stmnt = cash_flow_stmnt.set_index('fiscalYear')
cash_flow_stmnt_Metrics = cash_flow_stmnt.columns.values.tolist()

In [250]:
cash_flow_stmnt

,netIncome,depreciationAndAmortization,deferredIncomeTax,stockBasedCompensation,changeInWorkingCapital,accountsReceivables,inventory,accountsPayables,otherWorkingCapital,otherNonCashItems,...,netCashProvidedByFinancingActivities,effectOfForexChangesOnCash,netChangeInCash,cashAtEndOfPeriod,cashAtBeginningOfPeriod,operatingCashFlow,capitalExpenditure,freeCashFlow,incomeTaxesPaid,interestPaid
fiscalYear,,,,,,,,,,,,,,,,,,,,,
2024,93736000000,11445000000,0,11688000000,3651000000,-5144000000,-1046000000,6020000000,3821000000,-2266000000,...,-121983000000,0,-794000000,29943000000,30737000000,118254000000,-9447000000,108807000000,26102000000,0
2023,96995000000,11519000000,0,10833000000,-6577000000,-417000000,-1618000000,-1889000000,-2653000000,-2227000000,...,-108488000000,0,5760000000,30737000000,24977000000,110543000000,-10959000000,99584000000,18679000000,3803000000
2022,99803000000,11104000000,895000000,9038000000,1200000000,-9343000000,1484000000,9448000000,-389000000,111000000,...,-110749000000,0,-10952000000,24977000000,35929000000,122151000000,-10708000000,111443000000,19573000000,2865000000
2021,94680000000,11284000000,-4774000000,7906000000,-4911000000,-14028000000,-2642000000,12326000000,-567000000,-147000000,...,-93353000000,0,-3860000000,35929000000,39789000000,104038000000,-11085000000,92953000000,25385000000,2687000000
2020,57411000000,11056000000,-215000000,6829000000,5690000000,8470000000,-127000000,-4062000000,1409000000,-97000000,...,-86820000000,0,-10435000000,39789000000,50224000000,80674000000,-7309000000,73365000000,9501000000,3002000000