In [1]:
import requests
import warnings
from tqdm import tqdm, trange
import streamlit as st
import pandas as pd 
import yfinance as yf
from datetime import datetime
from dateutil.relativedelta import relativedelta
import plotly_express  as px
import plotly.graph_objects as go
import random
import unittest
import tables
import pickle
import pyarrow.parquet as pq
import pyarrow as pa
import plotly.io as pio
import math
import investpy
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import subprocess
import numpy as np
import matplotlib.pyplot as plt
import datetime
import time
from datetime import datetime
import pandas as pd
import streamlit as st
import yfinance as yf
import plotly.graph_objects as go
from streamlit_option_menu import option_menu
import math
import numpy as np
import sklearn.preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import subprocess
import time
import requests
import os
from stqdm import stqdm
from sklearn.manifold import TSNE
import plotly_express as px
warnings.simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

/opt/anaconda3/envs/stonksApp-env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
pio.templates.default = "plotly_dark"

In [4]:
tick = yf.Ticker("COST")

In [6]:
tick.info

{'address1': '999 Lake Drive',
 'city': 'Issaquah',
 'state': 'WA',
 'zip': '98027',
 'country': 'United States',
 'phone': '425 313 8100',
 'website': 'https://www.costco.com',
 'industry': 'Discount Stores',
 'industryKey': 'discount-stores',
 'industryDisp': 'Discount Stores',
 'sector': 'Consumer Defensive',
 'sectorKey': 'consumer-defensive',
 'sectorDisp': 'Consumer Defensive',
 'longBusinessSummary': 'Costco Wholesale Corporation, together with its subsidiaries, engages in the operation of membership warehouses in the United States, Puerto Rico, Canada, Mexico, Japan, the United Kingdom, Korea, Australia, Taiwan, China, Spain, France, Iceland, New Zealand, and Sweden. The company offers branded and private-label products in a range of merchandise categories. It offers merchandise, such as sundries, dry groceries, candies, coolers, freezers, deli, liquor, and tobacco; appliances, electronics, health and beauty aids, hardware, lawn and garden, sporting goods, tires, toys and seasonal products, office supplies, automotive care products, postages, tickets, apparel, small appliances, furniture, domestics, housewares, special order kiosks, and jewelry; and meat, produce, service deli, and bakery products. The company also operates gasoline, pharmacies, optical, food courts, hearing-aid centers, and tire installation centers; and offers business delivery, travel, grocery, and various other services online. It also operates e-commerce websites. The company was formerly known as Costco Companies, Inc. and changed its name to Costco Wholesale Corporation in August 1999. Costco Wholesale Corporation was founded in 1976 and is based in Issaquah, Washington.',
 'fullTimeEmployees': 333000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Ron M. Vachris',
   'age': 59,
   'title': 'President, CEO & Director',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 1568574,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Gary  Millerchip',
   'age': 52,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'totalPay': 4627773,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Javier  Polit',
   'age': 59,
   'title': 'Executive VP and CI&DO of Information Systems',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 3672119,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Pierre  Riel',
   'age': 61,
   'title': 'Executive VP & COO of International Division',
   'yearBorn': 1963,
   'fiscalYear': 2024,
   'totalPay': 1176061,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Russell D. Miller',
   'age': 67,
   'title': 'Senior EVP and COO of Warehouse Operations - U.S. & Mexico',
   'yearBorn': 1957,
   'fiscalYear': 2024,
   'totalPay': 969093,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Patrick J. Callans',
   'age': 62,
   'title': 'Executive Vice President of Administration',
   'yearBorn': 1962,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David  Sherwood',
   'title': 'Vice President of Finance & Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. John  Sullivan',
   'age': 64,
   'title': 'Executive VP, General Counsel & Corporate Secretary',
   'yearBorn': 1960,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Sheri  Flies',
   'title': 'Senior Vice President of Global Sustainability & Compliance',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Peter  Gruening',
   'title': 'Senior VP of Membership, Marketing & Member Service Centers',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 3,
 'compensationRisk': 5,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1738368000,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=83830&p=irol-irhome&cm_re=1_en-_-Bottom_Nav-_-Bottom_investor&lang=en-US',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 1062.54,
 'open': 1053.485,
 'dayLow': 1033.92,
 'dayHigh': 1053.64,
 'regularMarketPreviousClose': 1062.54,
 'regularMarketOpen': 1053.485,
 'regularMarketDayLow': 1033.92,
 'regularMarketDayHigh': 1053.64,
 'dividendRate': 4.64,
 'dividendYield': 0.44,
 'exDividendDate': 1738886400,
 'payoutRatio': 0.2644,
 'fiveYearAvgDividendYield': 0.67,
 'beta': 0.83,
 'trailingPE': 60.87235,
 'forwardPE': 52.58282,
 'volume': 1992704,
 'regularMarketVolume': 1992704,
 'averageVolume': 1986010,
 'averageVolume10days': 1781940,
 'averageDailyVolume10Day': 1781940,
 'bid': 1034.02,
 'ask': 1090.69,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 459359977472,
 'fiftyTwoWeekLow': 697.27,
 'fiftyTwoWeekHigh': 1078.23,
 'priceToSalesTrailing12Months': 1.7749269,
 'fiftyDayAverage': 976.449,
 'twoHundredDayAverage': 894.82324,
 'trailingAnnualDividendRate': 4.5,
 'trailingAnnualDividendYield': 0.0042351345,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 467963314176,
 'profitMargins': 0.02927,
 'floatShares': 442651514,
 'sharesOutstanding': 443899008,
 'sharesShort': 5889145,
 'sharesShortPriorMonth': 6541237,
 'sharesShortPreviousMonthDate': 1735603200,
 'dateShortInterest': 1738281600,
 'sharesPercentSharesOut': 0.013300001,
 'heldPercentInsiders': 0.00504,
 'heldPercentInstitutions': 0.72078,
 'shortRatio': 3.08,
 'shortPercentOfFloat': 0.013300001,
 'impliedSharesOutstanding': 443899008,
 'bookValue': 55.077,
 'priceToBook': 18.788786,
 'lastFiscalYearEnd': 1725148800,
 'nextFiscalYearEnd': 1756684800,
 'mostRecentQuarter': 1732406400,
 'earningsQuarterlyGrowth': 0.132,
 'netIncomeToCommon': 7576000000,
 'trailingEps': 17.0,
 'forwardEps': 19.68,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 947808000,
 'enterpriseToRevenue': 1.808,
 'enterpriseToEbitda': 39.722,
 '52WeekChange': 0.4468137,
 'SandP52WeekChange': 0.20780694,
 'lastDividendValue': 1.16,
 'lastDividendDate': 1738886400,
 'quoteType': 'EQUITY',
 'currentPrice': 1034.83,
 'targetHighPrice': 1200.0,
 'targetLowPrice': 560.0,
 'targetMeanPrice': 1044.6969,
 'targetMedianPrice': 1072.5,
 'recommendationMean': 1.97368,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 32,
 'totalCash': 11827000320,
 'totalCashPerShare': 26.643,
 'ebitda': 11781000192,
 'totalDebt': 8129999872,
 'quickRatio': 0.386,
 'currentRatio': 0.98,
 'totalRevenue': 258805006336,
 'debtToEquity': 33.25,
 'revenuePerShare': 582.954,
 'returnOnAssets': 0.080699995,
 'returnOnEquity': 0.29946,
 'grossProfits': 32795000832,
 'freeCashflow': 3041625088,
 'operatingCashflow': 9948000256,
 'earningsGrowth': 0.128,
 'revenueGrowth': 0.075,
 'grossMargins': 0.12672,
 'ebitdaMargins': 0.04552,
 'operatingMargins': 0.03533,
 'financialCurrency': 'USD',
 'symbol': 'COST',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POST',
 'regularMarketChangePercent': -2.6079097,
 'regularMarketPrice': 1034.83,
 'corporateActions': [],
 'postMarketTime': 1740086725,
 'regularMarketTime': 1740085201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_92817',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 521299800000,
 'shortName': 'Costco Wholesale Corporation',
 'longName': 'Costco Wholesale Corporation',
 'fiftyTwoWeekLowChangePercent': 0.48411652,
 'fiftyTwoWeekRange': '697.27 - 1078.23',
 'fiftyTwoWeekHighChange': -43.400024,
 'fiftyTwoWeekHighChangePercent': -0.040251177,
 'fiftyTwoWeekChangePercent': 44.68137,
 'dividendDate': 1740096000,
 'earningsTimestamp': 1741294800,
 'earningsTimestampStart': 1741294800,
 'earningsTimestampEnd': 1741294800,
 'earningsCallTimestampStart': 1741298400,
 'earningsCallTimestampEnd': 1741298400,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 17.0,
 'epsForward': 19.68,
 'epsCurrentYear': 18.13769,
 'priceEpsCurrentYear': 57.054123,
 'fiftyDayAverageChange': 58.38098,
 'fiftyDayAverageChangePercent': 0.059789076,
 'twoHundredDayAverageChange': 140.00671,
 'twoHundredDayAverageChangePercent': 0.15646298,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'postMarketChangePercent': 0.28265986,
 'postMarketPrice': 1037.755,
 'postMarketChange': 2.9250488,
 'regularMarketChange': -27.710083,
 'regularMarketDayRange': '1033.92 - 1053.64',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 1986010,
 'fiftyTwoWeekLowChange': 337.55994,
 'displayName': 'Costco Wholesale',
 'trailingPegRatio': 6.3633}

In [30]:
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
sp500_table = pd.read_html(url)[0]  # First table contains S&P 500 tickers

# Keep only the columns of interest
sp500_table = sp500_table[["Symbol"]]
sp500_list = sp500_table['Symbol'].to_list()

data = []



for ticker in tqdm(sp500_list):
    stock = yf.Ticker(ticker)
    
    # Extract relevant financial metrics
    try:
        market_cap = stock.info["marketCap"]
        revenue_growth = stock.info.get("revenueGrowth", None)
        earningsGrowth = stock.info.get("earningsGrowth", None)
        enterpriseToEbitda = stock.info.get("earningsGrowth", None)
        enterpriseToRevenue  = stock.info.get("earningsGrowth", None)
        ebitda_margin = stock.info.get("ebitdaMargins", None)
        operatingMargins = stock.info.get("operatingMargins", None)
        de = stock.info.get("debtToEquity", None)
        trailling_pe = stock.info.get("trailingPE", None)
        roe = stock.info.get("returnOnEquity", None)
        roa = stock.info.get("returnOnAssets", None)
        industry = stock.info.get("industryKey", None)
        sector = stock.info.get("sectorKey", None)
        longname = stock.info.get("longName", None)
        beta = stock.info.get("beta", None)
        trailingPegRatio = stock.info.get("trailingPegRatio", None)
        totalRevenue = stock.info.get("totalRevenue", None)
        ebitda = stock.info.get("ebitda", None)
        fiftytwoweekperf = stock.info.get("52WeekChange", None) 
        
        
        
        data.append([ticker,market_cap,revenue_growth,earningsGrowth,enterpriseToEbitda,enterpriseToRevenue,ebitda_margin,operatingMargins,de, trailling_pe, roe,roa,industry,sector, longname,beta,trailingPegRatio,totalRevenue,ebitda,fiftytwoweekperf ])
        
        
    except Exception as e:
        print(f"Error fetching data for {ticker}: {e}")
df = pd.DataFrame(data, columns=['Company', 'Market Cap', 'Rev Growth', 'NI Growth', 'EV/EBITDA', 'EV/Rev', 'EBITDA Margin', 'Operating Margin', 'Debt/Equity', 'PE', 'ROE','ROA', 'Industry', 'Sector', 'Name', 'Beta','Trailing PEG Ratio', 'Revenue', 'EBITDA', 'Yearly Performance' ])

 12%|█▏        | 61/503 [00:46<05:35,  1.32it/s]

Error fetching data for BRK.B: 'marketCap'

 15%|█▌        | 76/503 [00:58<05:55,  1.20it/s]

Error fetching data for BF.B: 'marketCap'

100%|██████████| 503/503 [06:30<00:00,  1.29it/s]

In [39]:
df = df.dropna()
df

,Market Cap,Rev Growth,NI Growth,EV/EBITDA,EV/Rev,EBITDA Margin,Operating Margin,Debt/Equity,PE,ROE,ROA,Trailing PEG Ratio,Revenue,EBITDA,Yearly Performance
0,80935526400,0.001,-0.217,-0.217,-0.217,0.22258,0.17671,350.770,20.562760,0.91851,0.05929,2.7125,24575000576,5.470000e+09,0.947731
1,9615022080,-0.077,-0.181,-0.181,-0.181,0.20364,0.15169,12.132,18.399448,0.28627,0.13533,1.6857,3818099968,7.775000e+08,-0.164372
4,240709713920,0.090,0.160,0.160,0.160,0.17116,0.16668,27.062,32.231155,0.26830,0.11460,3.0076,66361704448,1.135827e+10,0.050928
5,197926551552,0.111,0.176,0.176,0.176,0.39079,0.36300,42.935,36.846840,0.36313,0.16287,1.6021,21504999424,8.404000e+09,-0.149897
6,185010192384,0.242,-0.297,-0.297,-0.297,0.19973,0.13803,4.032,114.170000,0.02893,0.01902,0.4600,25784999936,5.150000e+09,-0.369350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,69593579520,0.158,0.674,0.674,0.674,0.08900,0.07639,38.996,43.031250,0.21247,0.01726,2.1865,8157000192,7.260000e+08,-0.148457
496,31517253632,0.065,0.211,0.211,0.211,0.19073,0.13032,18.526,35.542465,0.08453,0.04105,2.4767,8561999872,1.633000e+09,0.041247
498,16491696128,0.322,8.824,8.824,8.824,0.18811,0.17091,65.867,31.592522,0.15947,0.06261,1.1839,4981000192,9.370000e+08,0.161979
499,20630038528,0.043,-0.401,-0.401,-0.401,0.33485,0.22588,49.731,23.392776,0.07253,0.04593,1.4126,7678600192,2.571200e+09,-0.196048
500,70491414528,0.047,0.132,0.132,0.132,0.41368,0.33060,143.166,28.778793,0.51142,0.14870,2.7685,9255999488,3.829000e+09,-0.203498

In [38]:
df = df.drop(['Company', 'Industry', 'Sector', 'Name', 'Beta'], axis=1)
df

KeyError: "['Company', 'Industry', 'Sector', 'Name', 'Beta'] not found in axis"

In [40]:
import statsmodels.api as sm

In [56]:
df

,Market Cap,Rev Growth,NI Growth,EV/EBITDA,EV/Rev,EBITDA Margin,Operating Margin,Debt/Equity,PE,ROE,ROA,Trailing PEG Ratio,Revenue,EBITDA,Yearly Performance
0,80935526400,0.001,-0.217,-0.217,-0.217,0.22258,0.17671,350.770,20.562760,0.91851,0.05929,2.7125,24575000576,5.470000e+09,0.947731
1,9615022080,-0.077,-0.181,-0.181,-0.181,0.20364,0.15169,12.132,18.399448,0.28627,0.13533,1.6857,3818099968,7.775000e+08,-0.164372
4,240709713920,0.090,0.160,0.160,0.160,0.17116,0.16668,27.062,32.231155,0.26830,0.11460,3.0076,66361704448,1.135827e+10,0.050928
5,197926551552,0.111,0.176,0.176,0.176,0.39079,0.36300,42.935,36.846840,0.36313,0.16287,1.6021,21504999424,8.404000e+09,-0.149897
6,185010192384,0.242,-0.297,-0.297,-0.297,0.19973,0.13803,4.032,114.170000,0.02893,0.01902,0.4600,25784999936,5.150000e+09,-0.369350
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,69593579520,0.158,0.674,0.674,0.674,0.08900,0.07639,38.996,43.031250,0.21247,0.01726,2.1865,8157000192,7.260000e+08,-0.148457
496,31517253632,0.065,0.211,0.211,0.211,0.19073,0.13032,18.526,35.542465,0.08453,0.04105,2.4767,8561999872,1.633000e+09,0.041247
498,16491696128,0.322,8.824,8.824,8.824,0.18811,0.17091,65.867,31.592522,0.15947,0.06261,1.1839,4981000192,9.370000e+08,0.161979
499,20630038528,0.043,-0.401,-0.401,-0.401,0.33485,0.22588,49.731,23.392776,0.07253,0.04593,1.4126,7678600192,2.571200e+09,-0.196048
500,70491414528,0.047,0.132,0.132,0.132,0.41368,0.33060,143.166,28.778793,0.51142,0.14870,2.7685,9255999488,3.829000e+09,-0.203498

In [63]:
x_train = df.iloc[:,[1,2,4,5,6,9,10]]
x_train = sm.add_constant(x_train)
x_train

,const,Rev Growth,NI Growth,EV/Rev,EBITDA Margin,Operating Margin,ROE,ROA
0,1.0,0.001,-0.217,-0.217,0.22258,0.17671,0.91851,0.05929
1,1.0,-0.077,-0.181,-0.181,0.20364,0.15169,0.28627,0.13533
4,1.0,0.090,0.160,0.160,0.17116,0.16668,0.26830,0.11460
5,1.0,0.111,0.176,0.176,0.39079,0.36300,0.36313,0.16287
6,1.0,0.242,-0.297,-0.297,0.19973,0.13803,0.02893,0.01902
...,...,...,...,...,...,...,...,...
493,1.0,0.158,0.674,0.674,0.08900,0.07639,0.21247,0.01726
496,1.0,0.065,0.211,0.211,0.19073,0.13032,0.08453,0.04105
498,1.0,0.322,8.824,8.824,0.18811,0.17091,0.15947,0.06261
499,1.0,0.043,-0.401,-0.401,0.33485,0.22588,0.07253,0.04593
500,1.0,0.047,0.132,0.132,0.41368,0.33060,0.51142,0.14870

In [64]:
y_train = df.iloc[:,-1]
y_train

0      0.947731
1     -0.164372
4      0.050928
5     -0.149897
6     -0.369350
         ...
493   -0.148457
496    0.041247
498    0.161979
499   -0.196048
500   -0.203498
Name: Yearly Performance, Length: 310, dtype: float64

In [65]:
model = sm.OLS(y_train, x_train)

In [66]:
results = model.fit()

In [67]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     Yearly Performance   R-squared:                       0.155
Model:                            OLS   Adj. R-squared:                  0.138
Method:                 Least Squares   F-statistic:                     9.275
Date:                Thu, 20 Feb 2025   Prob (F-statistic):           2.44e-09
Time:                        23:52:38   Log-Likelihood:                -124.23
No. Observations:                 310   AIC:                             262.5
Df Residuals:                     303   BIC:                             288.6
Df Model:                           6
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                0.1069      0.051      2.076      0.039       0.006       0.208
Rev Growth           1.4682      0.215      6.837      0.000       1.046       1.891
NI Growth            0.0100      0.007      1.400      0.163      -0.004       0.024
EV/Rev               0.0100      0.007      1.400      0.163      -0.004       0.024
EBITDA Margin        0.0137      0.275      0.050      0.960      -0.527       0.555
Operating Margin     0.0173      0.386      0.045      0.964      -0.743       0.777
ROE                  0.0519      0.033      1.585      0.114      -0.013       0.116
ROA                 -1.1071      0.474     -2.337      0.020      -2.039      -0.175
==============================================================================
Omnibus:                      237.235   Durbin-Watson:                   1.873
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5443.724
Skew:                           2.858   Prob(JB):                         0.00
Kurtosis:                      22.717   Cond. No.                     2.27e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.99e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""